DjangoPsGu/urls.py
"""
Definition of urls for DjangoPsGu.
"""

from datetime import datetime
from django.urls import path
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from app import forms, views

from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings

urlpatterns = [
    path('', views.home, name='home'),
    path('contact/', views.contact, name='contact'),
    path('about/', views.about, name='about'),
    path('links/', views.links, name='links'),
    path('registration/', views.registration, name='registration'),
    path('feedback/', views.feedback, name='feedback'),
    path('blog/', views.blog, name='blog'),
    path('blogpost/<int:parametr>/',views.blogpost,name='blogpost'),
    path('newpost/',views.newpost,name='newpost'),
    path('videopost/',views.videopost,name='videopost'),
     path('products/', views.product_list, name='product_list'),
    path('cart/', views.cart_view, name='cart'),
    path('add_product/', views.add_product, name='add_product'),
    path('add_to_cart/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('remove_from_cart/<int:product_id>/', views.remove_from_cart, name='remove_from_cart'),
    path('clear_cart/', views.clear_cart, name='clear_cart'),
    path('checkout/', views.checkout, name='checkout'),
     path('cart/increase/<int:product_id>/', views.increase_quantity, name='increase_quantity'),
    path('cart/decrease/<int:product_id>/', views.decrease_quantity, name='decrease_quantity'),
     path('manage_products/', views.manage_products, name='manage_products'),
    path('manage_users/', views.manage_users, name='manage_users'),
    path('edit_user/<int:user_id>/', views.edit_user, name='edit_user'),
     path('create_order/', views.create_order, name='create_order'),
    path('order/<int:order_id>/', views.order_detail, name='order_detail'),
    path('manage_orders/', views.manage_orders, name='manage_orders'),
    path('login/',
         LoginView.as_view
         (
             template_name='app/login.html',
             authentication_form=forms.BootstrapAuthenticationForm,
             extra_context=
             {
                 'title': 'Войти',
                 'year' : datetime.now().year,
             }
         ),
         name='login'),
    path('logout/', LogoutView.as_view(next_page='/'), name='logout'),
    path('admin/', admin.site.urls),
]
urlpatterns += static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

app/models.py
"""
Definition of models.
"""

from django.db import models
from django.contrib import admin
from datetime import datetime 
from django.urls import reverse
from django.contrib.auth.models import User

class Blog(models.Model):

    title = models.CharField(max_length = 100, unique_for_date = "posted", verbose_name = "Заголовок")

    description = models.TextField(verbose_name = "Краткое содержание")

    content = models.TextField(verbose_name = "Полное содержание")

    posted = models.DateTimeField(default = datetime.now(), db_index = True, verbose_name = "Опубликована")

    author = models.ForeignKey(User, null=True, blank=True, on_delete = models.SET_NULL, verbose_name = "Автор")
    image = models.FileField(default = 'temp.jpg',verbose_name = 'Путь к картинке')

# Методы класса:

def get_absolute_url(self): # метод возвращает строку с URL-адресом записи

    return reverse("blogpost", args=[str(self.id)])

def __str__(self): # метод возвращает название, используемое для представления отдельных записей в административном разделе

    return self.title

# Метаданные – вложенный класс, который задает дополнительные параметры модели:

class Meta:

    db_table = "Posts" # имя таблицы для модели

    ordering = ["-posted"] # порядок сортировки данных в модели ("-" означает по убыванию)

    verbose_name = "статья блога" # имя, под которым модель будет отображаться в административном разделе (для одной статьи блога)

    verbose_name_plural = "статьи блога" # тоже для всех статей блога

admin.site.register(Blog)
class Comment(models.Model):
    text = models.TextField(verbose_name="Текст комментария")
    date = models.DateTimeField(default=datetime.now(), db_index=True, verbose_name="Дата комментария")
    author = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="Автор комментария")
    post = models.ForeignKey(Blog, on_delete=models.CASCADE, verbose_name="Статья комментария")
   

    # Методы класса:
    def __str__(self):  # метод возвращает название, используемое для представления отдельных записей в административном разделе
        return 'Комментарий %d из %s к %s' % (self.id, self.author, self.post)

    # Метаданные — вложенный класс, который задает дополнительные параметры модели:
    class Meta:
        db_table = "Comment"
        ordering = ["-date"]
        verbose_name = "Комментарий к статье блога"
        verbose_name_plural = "Комментарии к статьям блога"

class Product(models.Model):
    name = models.CharField(max_length=100, verbose_name="Название")
    description = models.TextField(verbose_name="Описание")
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name="Цена")
    image = models.FileField(upload_to='products/', verbose_name="Файл изображения товара")

    def __str__(self):
        return self.name

class Cart(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, verbose_name="Пользователь")
    products = models.ManyToManyField(Product, through='CartItem', verbose_name="Товары")

    def clear(self):
        self.cartitem_set.all().delete()

class CartItem(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return f"{self.product.name} x{self.quantity}"
admin.site.register(Comment)
admin.site.register(Product)
admin.site.register(Cart)
admin.site.register(CartItem)
# Create your models here.

class Order(models.Model):
    ORDER_TYPE_CHOICES = (
        ('in_progress', 'В процессе'),
        ('completed', 'Завершен'),
    )

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)  # Изменяем на ForeignKey
    order_type = models.CharField(max_length=20, choices=ORDER_TYPE_CHOICES, default='in_progress')
    created_at = models.DateTimeField(auto_now_add=True)

app/templates/app/about.html
{% extends "app/layout.html" %}

{% block content %}

<h2>О нас</h2>
<h3>
    В КЦдизайн мы верим, что каждый человек способен создавать красоту. Наша миссия – сделать процесс дизайна доступным и увлекательным для всех.<br /><br />

    Мы объединяем новейшие технологии, интуитивно понятный интерфейс и огромный выбор инструментов, чтобы вы могли воплотить свои идеи без ограничений. КЦдизайн – это платформа, где ваши фантазии превращаются в уникальные визуальные проекты, будь то дизайн для бизнеса, творчества или повседневной жизни.<br /><br />

    Мы ценим творчество и стремимся вдохновлять наших пользователей, предоставляя поддержку на каждом этапе создания. КЦдизайн – это не просто сервис, это сообщество людей, влюбленных в дизайн. Создавайте вместе с нами!
</h3>



{% endblock %}

app/templates/app/add_product.html
{% extends "app/layout.html" %}

{% block content %}
<h1>Добавить товар</h1>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Добавить</button>
</form>
{% endblock %}

app/templates/app/blog.html
{% extends "app/layout.html" %}

{% block content %}

<address>
    <h2>{{title}}</h2>
    <br />
    {%for post in posts%}
    <hr />
    <div>
        <h2>{{post.title}}</h2>
        <h4>{{post.posted}}</h4>
        <p>{{post.description}}</p>
        <p><a href="{%url 'blogpost' parametr=post.id %}">Читать далее</a></p>
    </div>
    {%endfor%}
{% endblock %}

app/templates/app/blogpost.html
{% extends "app/layout.html" %}

{% block content %}
<h2>{{post_1.title}}</h2>

{% if post_1.image %}
<img src="{{ post_1.image.url }}" alt="Картинка статьи блога" width="200" />
{% endif %}
<p>{{post_1.content|linebreaksbr}}</p><p><a href="{%url 'blog'%}">Назад</a></p>
{% if user.is_authenticated %}

<h3>Добавить комментарий</h3>

<form method="POST">
    {% csrf_token %} {# защита от атак CSRF#}

    <div>

        {{form.as_p}}

        <button type="submit" class="save btn btn-default"> Отправить комментарий </button>

    </div>

</form>

{% else %}

<h3> Для добавления своего комментария, пожалуйста, авторизуйтесь </h3>

{% endif %}
{% for comment in comments %}

<hr />

<h7> {{comment.date}} </h7>

<h5> {{comment.author}} </h5>

<p> {{comment.text|linebreaksbr}} </p>

{% endfor %}
    {% endblock %}

app/templates/app/cart.html
{% extends "app/layout.html" %}

{% block content %}
<h1>Корзина</h1>
<div class="cart">
    {% if cart %}
    <ul>
        {% for item in cart %}
        <li>
            {{ item.product.name }} — {{ item.quantity }} × {{ item.product.price }} руб. = {{ item.quantity|floatformat:2|add:item.product.price }} руб.
            <form method="post" action="{% url 'increase_quantity' item.product.id %}" style="display: inline;">
                {% csrf_token %}
                <button class="button-cus" type="submit">+</button>
            </form>
            <form method="post" action="{% url 'decrease_quantity' item.product.id %}" style="display: inline;">
                {% csrf_token %}
                <button class="button-cus" type="submit">-</button>
            </form>
            <form method="post" action="{% url 'remove_from_cart' item.product.id %}" style="display: inline;">
                {% csrf_token %}
                <button class="button-cus" type="submit">Удалить</button>
            </form>
        </li>
        {% endfor %}
    </ul>
    <p><strong>Итого:</strong> {{ total }} руб.</p>
    <form method="post" action="{% url 'clear_cart' %}">
        {% csrf_token %}
        <button class="button-cus" type="submit">Очистить корзину</button>
    </form>
    <form class="mt" method="post" action="{% url 'create_order' %}">
        {% csrf_token %}
        <button class="button-cus" type="submit">Оформить заказ</button>
    </form>
    {% else %}
    <p>Ваша корзина пуста.</p>
    {% endif %}
</div>
<style>
    li {
        list-style: none;
    }

    .mt {
        padding-top: 10px;
    }
</style>
{% endblock %}

app/templates/app/edit_user.html
{% extends "app/layout.html" %}

{% block content %}
<h1>Редактировать пользователя: {{ user.username }}</h1>

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Сохранить изменения</button>
</form>

<a href="{% url 'manage_users' %}">Назад к списку пользователей</a>
{% endblock %}

app/templates/app/index.html
{% extends "app/layout.html" %}

{% block content %}

<div class="jumbotron">
    <h1>КЦдизайн</h1>
    <p class="lead">KUдизайн- пространство, где ваши идеи превращаются в уникальные дизайны! </p>
</div>



    <div class="slider">
        <div class="slides">
            <div class="slide"><img src="https://s.tmimgcdn.com/scr/42700/42775-original.jpg" alt="Image 1"></div>
            <div class="slide"><img src="https://akrato.com/images/properties/dev/mobileversion.png" alt="Image 2"></div>
            <div class="slide"><img src="https://images.prismic.io/credoprint/a91f8afb-6f00-4d6f-a1a3-93d9e1b5b492_img2.jpg?auto=compress,format" alt="Image 3"></div>
        </div>
        <div class="controls">
            <button class="control prev">&#10094;</button>
            <button class="control next">&#10095;</button>
        </div>
    </div>


<style>
    
    .Pdown{
        margin-top:auto;
    }
    .jumbotron{
        background-color:#464AAA;
        border-radius:15px;
    }

</style>
<script>
    $(document).ready(function () {
        const $slides = $('.slides');
        const $slide = $('.slide');
        const slideCount = $slide.length;
        let currentIndex = 0;

        $('.next').click(function () {
            currentIndex = (currentIndex + 1) % slideCount;
            updateSlider();
        });

        $('.prev').click(function () {
            currentIndex = (currentIndex - 1 + slideCount) % slideCount;
            updateSlider();
        });

        function updateSlider() {
            const offset = -currentIndex * 100;
            $slides.css('transform', `translateX(${offset}%)`);
        }
    });
</script>
{% endblock %}

app/templates/app/layout.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }} - My Django Application</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'app/content/bootstrap.min.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'app/content/site.css' %}" />
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="{% static 'app/scripts/modernizr-2.6.2.js' %}"></script>
</head>

<body>
    <div class="navbar-cus">


        <a href="/" class="logo-main"><div> <img src="{% static 'app/content/img/logo.png' %}" alt="logo" /></div> </a>


        <ul class="ul-head">
            <li><a href="{% url 'home' %}">Главная</a></li>
            <li><a href="{% url 'about' %}">О нас</a></li>
            <li><a href="{% url 'contact' %}">Контакты</a></li>
            <li><a href="{% url 'links' %}">Полезные ресурсы</a></li>
            <li><a href="{% url 'feedback' %}">Обратная связь</a></li>
            <li><a href="{% url 'blog' %}">Блог</a></li>
            {% if user.is_authenticated %}
            <li><a href="{% url 'product_list' %}">Каталог</a></li>
            {% endif %}
            {%if user.is_superuser or is_manager_or_admin%}
            <li>
                <a href="{%url 'newpost'%}">Добавить статью</a>
            </li>
            <li>
                <a href="{%url 'manage_products'%}">Управление товарами</a>
            </li>
            <li>
                <a href="{%url 'manage_orders'%}">Управление заказами</a>
            </li>
            {% endif %}
            {%if user.is_superuser or is_admin%}
            <li>
                <a href="{%url 'manage_users'%}">Управление пользователями</a>
            </li>
            {% endif %}

            <li><a href="{%url 'videopost'%}">Видео</a></li>
            {% if not user.is_authenticated %}
            <li><a href="{% url 'registration' %}">Регистрация</a></li>
            {% endif %}
            {% if user.is_authenticated %}
            <li class="img-li">
                <a href="{%url 'cart'%}">корзина <img class="img-head" src="{% static 'app/content/img/cart.png' %}" alt="Alternate Text" /></a>
            </li>
            {% endif %}
        </ul>
        {% include 'app/loginpartial.html' %}
       

    </div>

    <div class="container-cus">
{% block content %}{% endblock %}
       
      
    </div>
    <style>
        .button-cus {
            border: none;
            border-radius: 25px;
            background-color: #58A5E3;
            color:white;
        }
        input:focus {
            outline: none;
            border: 1px solid gray;
        }
        
        textarea:focus {
            outline: none;
            border: 1px solid gray;
        }
        input {
            border: 1px solid gray;
            border-radius: 15px;
            padding-left: 10px;
        }
        textarea {
            border: 1px solid gray;
            border-radius: 15px;
            padding-left:10px;
        }
        #id_image {
            border: none
        }
        .img-li{
            display:flex;
           
        
            }
        .img-head{
            width:25px;
            height:25px;
           
        }
        
        
        div, h1, h2, h3 {
            color: white;
        }
        .NV{
            width:1200px;
            margin:0 auto;
        }
        body {
            background-color: #506BCB;
        }
        .Orange {
            background-color: #569edd;
            border-color: #569edd;
        }
        .navbar-cus {
            float: left;
            height: 100vh;
            width: 250px;
            background-color: #304059;
            position: fixed;
        }
        .container-cus {
            margin-left: 250px;
            width:calc(100vw - 295px);
            
            padding-left:15px;
            padding-top:15px;
            box-sizing:border-box;
        }
        .ul-head{
            width:100%;
            display:flex;
            flex-direction:column;
            padding:0px;
            

        }
            .ul-head li {
                list-style: none;
                width: 100%;
                font-size: 20px;
                border-bottom: 1px solid #58A5E3;
                
            }
                .ul-head li:hover {
                    background-color: #58A5E3;

                }
            .ul-head a {
                color: white;
                padding-left: 15px;
                width: 100%;
                display:block;
                text-decoration:none;
            }
            .logo-main {
                width: 100%;
                height: 85px;
                display: block;
            }
        .logo-main div{

            width:150px;
            height:100px;
           margin:0 auto;
        }
        .logo-main img{
            width:100%;
            height:100%;
        }
        .nav-content{
            width:200px;
           
            margin:0 auto;
        }

        .logoutForm {
            position: absolute;
            width:100%;
            bottom: 15px;
            display: flex;
            justify-content: space-around;
        }
        .log-out{
            color:white;
        }
        .log-in {
            position: absolute;
            width: 100%;
            bottom: 15px;
            color:white;
            text-align:center;
        }
        .edit_user a {
            padding: 3px;
            text-decoration: none;
        }
        .edit_user a:hover {
            color:white;
        }
    </style>
    <script src="{% static 'app/scripts/jquery-1.10.2.js' %}"></script>
    <script src="{% static 'app/scripts/bootstrap.js' %}"></script>
    <script src="{% static 'app/scripts/respond.js' %}"></script>
{% block scripts %}
    {% endblock %}

</body>
</html>

app/templates/app/login.html
{% extends "app/layout.html" %}

{% block content %}

<h2>{{ title }}</h2>
<div class="row">
    <div class="col-md-8">
        <section id="loginForm">
            <form action="." method="post" class="form-horizontal">
                {% csrf_token %}
                <h4>Локальный аккаунт.</h4>
                <hr />
                <div class="form-group">
                    <label for="id_username" class="col-md-2 control-label">Имя пользователя</label>
                    <div class="col-md-10">
                        {{ form.username }}
                    </div>
                </div>
                <div class="form-group">
                    <label for="id_password" class="col-md-2 control-label">Пароль</label>
                    <div class="col-md-10">
                        {{ form.password }}
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="hidden" name="next" value="/" />
                        <input type="submit" value="Войти" class="btn btn-default" />
                    </div>
                </div>
                {% if form.errors %}
                <p class="validation-summary-errors">Please enter a correct user name and password.</p>
                {% endif %}
            </form>
        </section>
    </div>
    <div class="col-md-4">
        <section id="socialLoginForm"></section>
    </div>
</div>

{% endblock %}


{% block scripts %}

    {% load static %}
<script src="{% static 'app/scripts/jquery.validate.min.js' %}"></script>

{% endblock %}

app/templates/app/manage_orders.html
{% extends "app/layout.html" %}

{% block content %}
<h1>Управление заказами</h1>
<table>
    <thead>
        <tr>
            <th>Заказ ID</th>
            <th>Пользователь</th>
            <th>Тип заказа</th>
            <th>Дата создания</th>
            <th>Действия</th>
        </tr>
    </thead>
    <tbody>
        {% for order in orders %}
        <tr>
            <td><a href="{% url 'order_detail' order.id %}">{{ order.id }}</a></td>
            <td>{{ order.user.username }}</td>
            <td>{{ order.get_order_type_display }}</td>
            <td>{{ order.created_at }}</td>
            <td>
                <form method="post" action="{% url 'manage_orders' %}">
                    {% csrf_token %}
                    <input type="hidden" name="order_id" value="{{ order.id }}">
                    <button type="submit" name="delete_order" class="button-cus">Удалить</button>
                    {% if order.order_type == 'in_progress' %}
                    <button type="submit" name="mark_completed" class="button-cus">Закрыть заказ</button>
                    {% endif %}
                </form>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

app/templates/app/manage_products.html
{% extends "app/layout.html" %}

{% block content %}
<h1>Управление товарами</h1>

<div class="h2-togl"><h2 id="toggle-add-product">Добавить товар</h2></div>
<form  class="add_product" style="display: none;" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" name="add_product">Добавить</button>
</form>

<div class="h2-togl"><h2  id="toggle-product-list">Список товаров</h2></div>
<div style="display: none;" class="edit_product">
    <table>
        <thead>
            <tr>
                <th>Название</th>
                <th>Цена</th>
                <th>Действия</th>
            </tr>
        </thead>
        <tbody>
            {% for product in products %}
            <tr>
                <td>{{ product.name }}</td>
                <td>{{ product.price }}</td>
                <td>
                    <form method="post" style="display:inline;">
                        {% csrf_token %}
                        <input type="hidden" name="product_id" value="{{ product.id }}">
                        <button class="button-cus" type="submit" name="delete_product">Удалить</button>
                    </form>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
<style>
    .h2-togl {
        background-color: #464AAA;
        height: 45px;
        border-radius: 15px;
        display: flex;
        align-items: center;
        padding: 8px;
        margin-top: 15px;
        margin-bottom: 5px;
        cursor: pointer;
    }

        .h2-togl h2 {
            margin: 0px;
        }
</style>
<script>$(document).ready(function () {
        // Переключение видимости формы добавления пользователя
        $('#toggle-add-product').on('click', function () {
            $('.add_product').slideToggle();
        });

        // Переключение видимости таблицы пользователей
    $('#toggle-product-list').on('click', function () {
            $('.edit_product').slideToggle();
        });
    });</script>
{% endblock %}

app/templates/app/manage_users.html
{% extends "app/layout.html" %}

{% block content %}
<h1>Управление пользователями</h1>

<div class="h2-togl"><h2 id="toggle-add-user">Добавить пользователя</h2></div>
<form class="add_user" method="post" style="display: none;">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" name="add_user">Добавить</button>
</form>

<div class="h2-togl"><h2 id="toggle-user-list">Список пользователей</h2></div>
<div style="display: none;" class="edit_user">
    <table >
        <thead>
            <tr>
                <th>Имя пользователя</th>
                <th>Email</th>
                <th>Действия</th>
            </tr>
        </thead>
        <tbody>
            {% for user in users %}
            <tr>
                <td>{{ user.username }}</td>
                <td>{{ user.email }}</td>
                <td>
                    <form method="post" style="display:inline;">
                        {% csrf_token %}
                        <input type="hidden" name="user_id" value="{{ user.id }}">
                        <button class="button-cus" type="submit" name="delete_user">Удалить</button>
                    </form>
                    <a class="button-cus  button-cus1" href="{% url 'edit_user' user.id %}">Изменить</a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
<style>

   
    .h2-togl {
        background-color: #464AAA;
        height: 45px;
        border-radius: 15px;
        display: flex;
        align-items: center;
        padding: 8px;
        margin-top: 15px;
        margin-bottom: 5px;
        cursor: pointer;
    }
    .h2-togl h2{
        margin:0px;
    }
</style>
<script>$(document).ready(function () {
        // Переключение видимости формы добавления пользователя
        $('#toggle-add-user').on('click', function () {
            $('.add_user').slideToggle();
        });

        // Переключение видимости таблицы пользователей
        $('#toggle-user-list').on('click', function () {
            $('.edit_user').slideToggle();
        });
    });</script>
{% endblock %}

app/templates/app/order_detail.html
{% extends "app/layout.html" %}

{% block content %}
<h1>Детали заказа #{{ order.id }}</h1>
<p>Дата создания: {{ order.created_at }}</p>
<p>Тип заказа: {{ order.get_order_type_display }}</p>

<h2>Товары в заказе:</h2>
<table>
    <thead>
        <tr>
            <th>Название товара</th>
            <th>Количество</th>
            <th>Цена</th>
            <th>Сумма</th>
        </tr>
    </thead>
    <tbody>
        {% for item in order.cart.cartitem_set.all %}
        <tr>
            <td>{{ item.product.name }}</td>
            <td>{{ item.quantity }}</td>
            <td>{{ item.product.price }}</td>
         
        </tr>
        {% empty %}
        <tr>
            <td colspan="4">В вашем заказе нет товаров.</td>
        </tr>
        {% endfor %}
    </tbody>
</table>

<p><a href="{% url 'cart' %}">Вернуться в корзину</a></p>
{% endblock %}

app/templates/app/registration.html
{% extends "app/layout.html" %}

{% block content %}
<h2>Регистрация пользователя</h2>
<form class="form-reg" method="post">
    <div>
        {% csrf_token %}
        {{ regform.as_p }}
        <button class="reg-b" type="submit" class="save btn btn-defauldt">Зарегистрировать</button>
    </div>
</form>
<style>
    .form-reg {
        background-color: #58A5E3;
        border-radius: 15px;
        padding: 10px;
    }
    .reg-b{
        background-color:white;
        border:1px solid gray;
        border-radius:10px;
    }
</style>

{% endblock %}